### ISSUE TITLE
Why is website required?

### ISSUE THREAD

**Issue by Artanis** [sindresorhus/generator-electron#14]
It's only used in three places: `package.json`, `license`, and `readme.md`.

These locations could easily be edited in by the user later, if they don't want to immediately provide a website url.

**Comment by sindresorhus** [comment]
Why not? If you don't have one you can just provide your GitHub/Twitter profile.

**Comment by Artanis** [comment]
That makes sense. I was thinking more along the lines of project webpage, which might not exist so early on.
