### ISSUE TITLE
No documentation?

### ISSUE THREAD

**Issue by Frondor** [sindresorhus/generator-electron#18]
Is this generator intended for the boilerplate only? No build process? I've tried `npm build` but nothing happens, unlike `npm test` and `npm start` which works just fine. I'm using latest version

**Comment by sindresorhus** [comment]
It's in the readme that was generated for you. Try `npm build` → `npm run build`.

If there's anything else you think could be improved, let me know ;)

**Comment by Frondor** [comment]
I tried that, but it isn't working: http://pastebin.com/82Vnx97J (npm-debug.log)
https://i.gyazo.com/9ff5e759881718c56604bc9d66c94b1b.png

**Comment by deltaidea** [comment]
Got the same error, solution: go to `package.json` and manually fix the `"build"` script:
- replace `$npm_package_productName` with your project name
- replace `$npm_package_electronVersion` with your Electron version ([latest](https://github.com/atom/electron/releases/latest) recommended)

So it should look like this:

``` JSON
"build": "electron-packager . my-app --out=dist --ignore='^/dist$' --prune --asar --all --version=0.34.3"
```

**Comment by sindresorhus** [comment]
This is no longer applicable.
