### ISSUE TITLE
(electron) companyName error

### ISSUE THREAD

**Issue by nguyenDalex** [sindresorhus/generator-electron#19]
I get this when i try npm start
companyName is now a required option to crashReporter.start

**Comment by santomegonzalo** [comment]
I'm having the same problem... I added into package.json but didn't work...

**Comment by kevva** [comment]
You need to provide a `companyName` and a `submitURL` for it to work https://github.com/atom/electron/blob/master/docs/api/crash-reporter.md#crashreporterstartoptions.

**Comment by sindresorhus** [comment]
Ended up removing the crashReporter. Turns out you need to set up your own server. I don't think most will do that.
