### ISSUE TITLE
Integrate watching files plugin

### ISSUE THREAD

**Issue by lvarayut** [sindresorhus/generator-electron#23]
It would be great to integrate [chokidar](https://github.com/paulmillr/chokidar) to watch files and automatically restart an electron app on any changes. So, we don't need to manually restart the app while developing it.

**Comment by sindresorhus** [comment]
You can press Cmd+R to refresh any changes in the renderer btw. `chokidar` is too low-level, but if you can find something like `nodemon` for Electron, I would be happy to consider including it.

**Comment by lvarayut** [comment]
Thanks for your response. [electron-reload](https://github.com/yan-foto/electron-reload) or [electromon](https://github.com/simonhochrein/electromon) might do the trick.

**Comment by sindresorhus** [comment]
This project is now archived.
