### ISSUE TITLE
Cannot generate projects with Nodist

### ISSUE THREAD

**Issue by gigouni** [sindresorhus/generator-electron#30]
Hi,

When trying to install the generator and run it, some issues are popping.

![image](https://user-images.githubusercontent.com/9595466/95062086-c1ed1f00-06fc-11eb-9465-15354b5a5102.png)

It seems the Nodist usage is not compatible. It does not find the $NODE_PATH while it exists and the generation fails for missing files.

Do you have any clue?

Thanks

**Comment by sindresorhus** [comment]
This is a problem with the `yo` command, not this generator.

https://github.com/yeoman/yo
