### ISSUE TITLE
ES6 support

### ISSUE THREAD

**Issue by timotius02** [sindresorhus/generator-electron#5]
Just wondering where in the generator does it add the ES6 support or if it just comes natively in Electron?

**Comment by sindresorhus** [comment]
The current limited ES6 usage comes natively, since Electron uses iojs. You can find supported ES6 features here: https://iojs.org/en/es6.html

Though I plan to integrate [babel](https://babeljs.io/) so we can use any ES6 feature.

**Comment by joseluisq** [comment]
:+1:

**Comment by sindresorhus** [comment]
Electron now supports most of ES6, and will soon support all of it. I don't want to setup up Babel with so little gain. If you want it, you can use https://github.com/electronjs/electron-compile.
