### ISSUE TITLE
Question: auto deploy on electron-boilerplate

### ISSUE THREAD

**Issue by zckrs** [sindresorhus/generator-electron#6]
Hi @sindresorhus 

Do you have a script or process to commit/push on [electron-boilerplate](https://github.com/sindresorhus/electron-boilerplate) foreach success Travis build on master branch ? 

Or you do that manually ?

**Comment by sindresorhus** [comment]
I update them separately manually as they differ slightly. Could probably automate it, but that would take more time than the little time I use to update them once in a while.
